// Number of persons directly affected by disasters, by Pacific Island Country/Territory and year. Source: directly_affected_persons.xlsx
const rawAffectedPersonsData = [
  { country: "American Samoa", year: 2005, personsAffected: null },
  { country: "American Samoa", year: 2006, personsAffected: null },
  { country: "American Samoa", year: 2007, personsAffected: null },
  { country: "American Samoa", year: 2008, personsAffected: null },
  { country: "American Samoa", year: 2009, personsAffected: 0 },
  { country: "American Samoa", year: 2010, personsAffected: null },
  { country: "American Samoa", year: 2011, personsAffected: null },
  { country: "American Samoa", year: 2012, personsAffected: null },
  { country: "American Samoa", year: 2013, personsAffected: null },
  { country: "American Samoa", year: 2014, personsAffected: 0 },
  { country: "American Samoa", year: 2015, personsAffected: 0 },
  { country: "American Samoa", year: 2016, personsAffected: null },
  { country: "American Samoa", year: 2017, personsAffected: null },
  { country: "American Samoa", year: 2018, personsAffected: 3800 },
  { country: "American Samoa", year: 2019, personsAffected: 12 },
  { country: "American Samoa", year: 2020, personsAffected: 232 },
  { country: "American Samoa", year: 2021, personsAffected: null },
  { country: "American Samoa", year: 2022, personsAffected: null },
  { country: "American Samoa", year: 2023, personsAffected: null },
  { country: "Cook Islands", year: 2005, personsAffected: 1121 },
  { country: "Cook Islands", year: 2006, personsAffected: null },
  { country: "Cook Islands", year: 2007, personsAffected: 0 },
  { country: "Cook Islands", year: 2008, personsAffected: null },
  { country: "Cook Islands", year: 2009, personsAffected: 0 },
  { country: "Cook Islands", year: 2010, personsAffected: 4443 },
  { country: "Cook Islands", year: 2011, personsAffected: null },
  { country: "Cook Islands", year: 2012, personsAffected: null },
  { country: "Cook Islands", year: 2013, personsAffected: null },
  { country: "Cook Islands", year: 2014, personsAffected: null },
  { country: "Cook Islands", year: 2015, personsAffected: null },
  { country: "Cook Islands", year: 2016, personsAffected: null },
  { country: "Cook Islands", year: 2017, personsAffected: null },
  { country: "Cook Islands", year: 2018, personsAffected: null },
  { country: "Cook Islands", year: 2019, personsAffected: null },
  { country: "Cook Islands", year: 2020, personsAffected: 0 },
  { country: "Cook Islands", year: 2021, personsAffected: null },
  { country: "Cook Islands", year: 2022, personsAffected: null },
  { country: "Cook Islands", year: 2023, personsAffected: null },
  { country: "Fiji", year: 2005, personsAffected: 0 },
  { country: "Fiji", year: 2006, personsAffected: 60 },
  { country: "Fiji", year: 2007, personsAffected: 12 },
  { country: "Fiji", year: 2008, personsAffected: 804 },
  { country: "Fiji", year: 2009, personsAffected: 12692 },
  { country: "Fiji", year: 2010, personsAffected: 6644 },
  { country: "Fiji", year: 2011, personsAffected: 344 },
  { country: "Fiji", year: 2012, personsAffected: 37085 },
  { country: "Fiji", year: 2013, personsAffected: 0 },
  { country: "Fiji", year: 2014, personsAffected: 0 },
  { country: "Fiji", year: 2015, personsAffected: 0 },
  { country: "Fiji", year: 2016, personsAffected: 633584 },
  { country: "Fiji", year: 2017, personsAffected: 0 },
  { country: "Fiji", year: 2018, personsAffected: 155726 },
  { country: "Fiji", year: 2019, personsAffected: 78045 },
  { country: "Fiji", year: 2020, personsAffected: 235921 },
  { country: "Fiji", year: 2021, personsAffected: 78030 },
  { country: "Fiji", year: 2022, personsAffected: 1787 },
  { country: "Fiji", year: 2023, personsAffected: null },
  { country: "French Polynesia", year: 2005, personsAffected: null },
  { country: "French Polynesia", year: 2006, personsAffected: null },
  { country: "French Polynesia", year: 2007, personsAffected: 0 },
  { country: "French Polynesia", year: 2008, personsAffected: null },
  { country: "French Polynesia", year: 2009, personsAffected: null },
  { country: "French Polynesia", year: 2010, personsAffected: null },
  { country: "French Polynesia", year: 2011, personsAffected: null },
  { country: "French Polynesia", year: 2012, personsAffected: null },
  { country: "French Polynesia", year: 2013, personsAffected: null },
  { country: "French Polynesia", year: 2014, personsAffected: null },
  { country: "French Polynesia", year: 2015, personsAffected: null },
  { country: "French Polynesia", year: 2016, personsAffected: null },
  { country: "French Polynesia", year: 2017, personsAffected: null },
  { country: "French Polynesia", year: 2018, personsAffected: null },
  { country: "French Polynesia", year: 2019, personsAffected: null },
  { country: "French Polynesia", year: 2020, personsAffected: null },
  { country: "French Polynesia", year: 2021, personsAffected: null },
  { country: "French Polynesia", year: 2022, personsAffected: null },
  { country: "French Polynesia", year: 2023, personsAffected: null },
  { country: "Guam", year: 2005, personsAffected: null },
  { country: "Guam", year: 2006, personsAffected: null },
  { country: "Guam", year: 2007, personsAffected: null },
  { country: "Guam", year: 2008, personsAffected: null },
  { country: "Guam", year: 2009, personsAffected: null },
  { country: "Guam", year: 2010, personsAffected: null },
  { country: "Guam", year: 2011, personsAffected: null },
  { country: "Guam", year: 2012, personsAffected: null },
  { country: "Guam", year: 2013, personsAffected: null },
  { country: "Guam", year: 2014, personsAffected: null },
  { country: "Guam", year: 2015, personsAffected: 0 },
  { country: "Guam", year: 2016, personsAffected: null },
  { country: "Guam", year: 2017, personsAffected: null },
  { country: "Guam", year: 2018, personsAffected: null },
  { country: "Guam", year: 2019, personsAffected: null },
  { country: "Guam", year: 2020, personsAffected: null },
  { country: "Guam", year: 2021, personsAffected: null },
  { country: "Guam", year: 2022, personsAffected: null },
  { country: "Guam", year: 2023, personsAffected: null },
  { country: "Kiribati", year: 2005, personsAffected: null },
  { country: "Kiribati", year: 2006, personsAffected: null },
  { country: "Kiribati", year: 2007, personsAffected: null },
  { country: "Kiribati", year: 2008, personsAffected: 85 },
  { country: "Kiribati", year: 2009, personsAffected: null },
  { country: "Kiribati", year: 2010, personsAffected: null },
  { country: "Kiribati", year: 2011, personsAffected: null },
  { country: "Kiribati", year: 2012, personsAffected: null },
  { country: "Kiribati", year: 2013, personsAffected: null },
  { country: "Kiribati", year: 2014, personsAffected: 44 },
  { country: "Kiribati", year: 2015, personsAffected: 2507 },
  { country: "Kiribati", year: 2016, personsAffected: 0 },
  { country: "Kiribati", year: 2017, personsAffected: null },
  { country: "Kiribati", year: 2018, personsAffected: 0 },
  { country: "Kiribati", year: 2019, personsAffected: 3 },
  { country: "Kiribati", year: 2020, personsAffected: 15 },
  { country: "Kiribati", year: 2021, personsAffected: 333 },
  { country: "Kiribati", year: 2022, personsAffected: null },
  { country: "Kiribati", year: 2023, personsAffected: null },
  { country: "Marshall Islands", year: 2005, personsAffected: null },
  { country: "Marshall Islands", year: 2006, personsAffected: 0 },
  { country: "Marshall Islands", year: 2007, personsAffected: null },
  { country: "Marshall Islands", year: 2008, personsAffected: 96 },
  { country: "Marshall Islands", year: 2009, personsAffected: null },
  { country: "Marshall Islands", year: 2010, personsAffected: null },
  { country: "Marshall Islands", year: 2011, personsAffected: 0 },
  { country: "Marshall Islands", year: 2012, personsAffected: null },
  { country: "Marshall Islands", year: 2013, personsAffected: 0 },
  { country: "Marshall Islands", year: 2014, personsAffected: 280 },
  { country: "Marshall Islands", year: 2015, personsAffected: 0 },
  { country: "Marshall Islands", year: 2016, personsAffected: 27452 },
  { country: "Marshall Islands", year: 2017, personsAffected: 7029 },
  { country: "Marshall Islands", year: 2018, personsAffected: 0 },
  { country: "Marshall Islands", year: 2019, personsAffected: 35844 },
  { country: "Marshall Islands", year: 2020, personsAffected: 56718 },
  { country: "Marshall Islands", year: 2021, personsAffected: 0 },
  { country: "Marshall Islands", year: 2022, personsAffected: 52914 },
  { country: "Marshall Islands", year: 2023, personsAffected: null },
  { country: "Micronesia (Federated States of)", year: 2005, personsAffected: null },
  { country: "Micronesia (Federated States of)", year: 2006, personsAffected: 0 },
  { country: "Micronesia (Federated States of)", year: 2007, personsAffected: null },
  { country: "Micronesia (Federated States of)", year: 2008, personsAffected: 0 },
  { country: "Micronesia (Federated States of)", year: 2009, personsAffected: 0 },
  { country: "Micronesia (Federated States of)", year: 2010, personsAffected: null },
  { country: "Micronesia (Federated States of)", year: 2011, personsAffected: 0 },
  { country: "Micronesia (Federated States of)", year: 2012, personsAffected: null },
  { country: "Micronesia (Federated States of)", year: 2013, personsAffected: null },
  { country: "Micronesia (Federated States of)", year: 2014, personsAffected: null },
  { country: "Micronesia (Federated States of)", year: 2015, personsAffected: 7600 },
  { country: "Micronesia (Federated States of)", year: 2016, personsAffected: 0 },
  { country: "Micronesia (Federated States of)", year: 2017, personsAffected: 0 },
  { country: "Micronesia (Federated States of)", year: 2018, personsAffected: 1266 },
  { country: "Micronesia (Federated States of)", year: 2019, personsAffected: 20732 },
  { country: "Micronesia (Federated States of)", year: 2020, personsAffected: 0 },
  { country: "Micronesia (Federated States of)", year: 2021, personsAffected: 15010 },
  { country: "Micronesia (Federated States of)", year: 2022, personsAffected: null },
  { country: "Micronesia (Federated States of)", year: 2023, personsAffected: null },
  { country: "Naoero", year: 2005, personsAffected: null },
  { country: "Naoero", year: 2006, personsAffected: null },
  { country: "Naoero", year: 2007, personsAffected: null },
  { country: "Naoero", year: 2008, personsAffected: null },
  { country: "Naoero", year: 2009, personsAffected: null },
  { country: "Naoero", year: 2010, personsAffected: null },
  { country: "Naoero", year: 2011, personsAffected: null },
  { country: "Naoero", year: 2012, personsAffected: null },
  { country: "Naoero", year: 2013, personsAffected: null },
  { country: "Naoero", year: 2014, personsAffected: null },
  { country: "Naoero", year: 2015, personsAffected: null },
  { country: "Naoero", year: 2016, personsAffected: null },
  { country: "Naoero", year: 2017, personsAffected: null },
  { country: "Naoero", year: 2018, personsAffected: null },
  { country: "Naoero", year: 2019, personsAffected: 63 },
  { country: "Naoero", year: 2020, personsAffected: 1133 },
  { country: "Naoero", year: 2021, personsAffected: 4 },
  { country: "Naoero", year: 2022, personsAffected: 5393 },
  { country: "Naoero", year: 2023, personsAffected: null },
  { country: "New Caledonia", year: 2005, personsAffected: null },
  { country: "New Caledonia", year: 2006, personsAffected: null },
  { country: "New Caledonia", year: 2007, personsAffected: null },
  { country: "New Caledonia", year: 2008, personsAffected: null },
  { country: "New Caledonia", year: 2009, personsAffected: 0 },
  { country: "New Caledonia", year: 2010, personsAffected: null },
  { country: "New Caledonia", year: 2011, personsAffected: 0 },
  { country: "New Caledonia", year: 2012, personsAffected: null },
  { country: "New Caledonia", year: 2013, personsAffected: null },
  { country: "New Caledonia", year: 2014, personsAffected: null },
  { country: "New Caledonia", year: 2015, personsAffected: null },
  { country: "New Caledonia", year: 2016, personsAffected: null },
  { country: "New Caledonia", year: 2017, personsAffected: 4 },
  { country: "New Caledonia", year: 2018, personsAffected: 0 },
  { country: "New Caledonia", year: 2019, personsAffected: 1 },
  { country: "New Caledonia", year: 2020, personsAffected: 2 },
  { country: "New Caledonia", year: 2021, personsAffected: null },
  { country: "New Caledonia", year: 2022, personsAffected: null },
  { country: "New Caledonia", year: 2023, personsAffected: null },
  { country: "Niue", year: 2005, personsAffected: null },
  { country: "Niue", year: 2006, personsAffected: null },
  { country: "Niue", year: 2007, personsAffected: null },
  { country: "Niue", year: 2008, personsAffected: null },
  { country: "Niue", year: 2009, personsAffected: null },
  { country: "Niue", year: 2010, personsAffected: null },
  { country: "Niue", year: 2011, personsAffected: null },
  { country: "Niue", year: 2012, personsAffected: 0 },
  { country: "Niue", year: 2013, personsAffected: null },
  { country: "Niue", year: 2014, personsAffected: null },
  { country: "Niue", year: 2015, personsAffected: null },
  { country: "Niue", year: 2016, personsAffected: null },
  { country: "Niue", year: 2017, personsAffected: null },
  { country: "Niue", year: 2018, personsAffected: null },
  { country: "Niue", year: 2019, personsAffected: null },
  { country: "Niue", year: 2020, personsAffected: 0 },
  { country: "Niue", year: 2021, personsAffected: null },
  { country: "Niue", year: 2022, personsAffected: null },
  { country: "Niue", year: 2023, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2005, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2006, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2007, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2008, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2009, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2010, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2011, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2012, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2013, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2014, personsAffected: 0 },
  { country: "Northern Mariana Islands", year: 2015, personsAffected: 0 },
  { country: "Northern Mariana Islands", year: 2016, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2017, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2018, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2019, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2020, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2021, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2022, personsAffected: null },
  { country: "Northern Mariana Islands", year: 2023, personsAffected: null },
  { country: "Palau", year: 2005, personsAffected: null },
  { country: "Palau", year: 2006, personsAffected: null },
  { country: "Palau", year: 2007, personsAffected: null },
  { country: "Palau", year: 2008, personsAffected: null },
  { country: "Palau", year: 2009, personsAffected: 0 },
  { country: "Palau", year: 2010, personsAffected: null },
  { country: "Palau", year: 2011, personsAffected: 0 },
  { country: "Palau", year: 2012, personsAffected: 1528 },
  { country: "Palau", year: 2013, personsAffected: null },
  { country: "Palau", year: 2014, personsAffected: null },
  { country: "Palau", year: 2015, personsAffected: 0 },
  { country: "Palau", year: 2016, personsAffected: 11009 },
  { country: "Palau", year: 2017, personsAffected: null },
  { country: "Palau", year: 2018, personsAffected: null },
  { country: "Palau", year: 2019, personsAffected: null },
  { country: "Palau", year: 2020, personsAffected: null },
  { country: "Palau", year: 2021, personsAffected: 24220 },
  { country: "Palau", year: 2022, personsAffected: 780 },
  { country: "Palau", year: 2023, personsAffected: null },
  { country: "Papua New Guinea", year: 2005, personsAffected: 2 },
  { country: "Papua New Guinea", year: 2006, personsAffected: 216 },
  { country: "Papua New Guinea", year: 2007, personsAffected: 56284 },
  { country: "Papua New Guinea", year: 2008, personsAffected: 36393 },
  { country: "Papua New Guinea", year: 2009, personsAffected: 580 },
  { country: "Papua New Guinea", year: 2010, personsAffected: 0 },
  { country: "Papua New Guinea", year: 2011, personsAffected: 0 },
  { country: "Papua New Guinea", year: 2012, personsAffected: 172 },
  { country: "Papua New Guinea", year: 2013, personsAffected: 264 },
  { country: "Papua New Guinea", year: 2014, personsAffected: 0 },
  { country: "Papua New Guinea", year: 2015, personsAffected: 0 },
  { country: "Papua New Guinea", year: 2016, personsAffected: null },
  { country: "Papua New Guinea", year: 2017, personsAffected: null },
  { country: "Papua New Guinea", year: 2018, personsAffected: null },
  { country: "Papua New Guinea", year: 2019, personsAffected: 2100 },
  { country: "Papua New Guinea", year: 2020, personsAffected: 3297 },
  { country: "Papua New Guinea", year: 2021, personsAffected: null },
  { country: "Papua New Guinea", year: 2022, personsAffected: null },
  { country: "Papua New Guinea", year: 2023, personsAffected: null },
  { country: "Samoa", year: 2005, personsAffected: 0 },
  { country: "Samoa", year: 2006, personsAffected: 0 },
  { country: "Samoa", year: 2007, personsAffected: null },
  { country: "Samoa", year: 2008, personsAffected: 0 },
  { country: "Samoa", year: 2009, personsAffected: 6332 },
  { country: "Samoa", year: 2010, personsAffected: null },
  { country: "Samoa", year: 2011, personsAffected: null },
  { country: "Samoa", year: 2012, personsAffected: 0 },
  { country: "Samoa", year: 2013, personsAffected: 0 },
  { country: "Samoa", year: 2014, personsAffected: 0 },
  { country: "Samoa", year: 2015, personsAffected: 0 },
  { country: "Samoa", year: 2016, personsAffected: 0 },
  { country: "Samoa", year: 2017, personsAffected: null },
  { country: "Samoa", year: 2018, personsAffected: 383 },
  { country: "Samoa", year: 2019, personsAffected: 5700 },
  { country: "Samoa", year: 2020, personsAffected: 195 },
  { country: "Samoa", year: 2021, personsAffected: 15 },
  { country: "Samoa", year: 2022, personsAffected: 16607 },
  { country: "Samoa", year: 2023, personsAffected: 138 },
  { country: "Solomon Islands", year: 2005, personsAffected: null },
  { country: "Solomon Islands", year: 2006, personsAffected: 0 },
  { country: "Solomon Islands", year: 2007, personsAffected: 21343 },
  { country: "Solomon Islands", year: 2008, personsAffected: 0 },
  { country: "Solomon Islands", year: 2009, personsAffected: 68 },
  { country: "Solomon Islands", year: 2010, personsAffected: 1456 },
  { country: "Solomon Islands", year: 2011, personsAffected: 36 },
  { country: "Solomon Islands", year: 2012, personsAffected: 216 },
  { country: "Solomon Islands", year: 2013, personsAffected: 7577 },
  { country: "Solomon Islands", year: 2014, personsAffected: 14831 },
  { country: "Solomon Islands", year: 2015, personsAffected: 185886 },
  { country: "Solomon Islands", year: 2016, personsAffected: 60858 },
  { country: "Solomon Islands", year: 2017, personsAffected: 51465 },
  { country: "Solomon Islands", year: 2018, personsAffected: 194155 },
  { country: "Solomon Islands", year: 2019, personsAffected: 1834 },
  { country: "Solomon Islands", year: 2020, personsAffected: 2339 },
  { country: "Solomon Islands", year: 2021, personsAffected: 240 },
  { country: "Solomon Islands", year: 2022, personsAffected: 20080 },
  { country: "Solomon Islands", year: 2023, personsAffected: null },
  { country: "Tokelau", year: 2005, personsAffected: 0 },
  { country: "Tokelau", year: 2006, personsAffected: null },
  { country: "Tokelau", year: 2007, personsAffected: null },
  { country: "Tokelau", year: 2008, personsAffected: null },
  { country: "Tokelau", year: 2009, personsAffected: 0 },
  { country: "Tokelau", year: 2010, personsAffected: null },
  { country: "Tokelau", year: 2011, personsAffected: 0 },
  { country: "Tokelau", year: 2012, personsAffected: null },
  { country: "Tokelau", year: 2013, personsAffected: null },
  { country: "Tokelau", year: 2014, personsAffected: null },
  { country: "Tokelau", year: 2015, personsAffected: null },
  { country: "Tokelau", year: 2016, personsAffected: null },
  { country: "Tokelau", year: 2017, personsAffected: null },
  { country: "Tokelau", year: 2018, personsAffected: null },
  { country: "Tokelau", year: 2019, personsAffected: null },
  { country: "Tokelau", year: 2020, personsAffected: null },
  { country: "Tokelau", year: 2021, personsAffected: null },
  { country: "Tokelau", year: 2022, personsAffected: null },
  { country: "Tokelau", year: 2023, personsAffected: null },
  { country: "Tonga", year: 2005, personsAffected: 0 },
  { country: "Tonga", year: 2006, personsAffected: 0 },
  { country: "Tonga", year: 2007, personsAffected: 0 },
  { country: "Tonga", year: 2008, personsAffected: 0 },
  { country: "Tonga", year: 2009, personsAffected: 7 },
  { country: "Tonga", year: 2010, personsAffected: 0 },
  { country: "Tonga", year: 2011, personsAffected: 345 },
  { country: "Tonga", year: 2012, personsAffected: 0 },
  { country: "Tonga", year: 2013, personsAffected: 0 },
  { country: "Tonga", year: 2014, personsAffected: 4520 },
  { country: "Tonga", year: 2015, personsAffected: 0 },
  { country: "Tonga", year: 2016, personsAffected: 0 },
  { country: "Tonga", year: 2017, personsAffected: 0 },
  { country: "Tonga", year: 2018, personsAffected: 84311 },
  { country: "Tonga", year: 2019, personsAffected: 640 },
  { country: "Tonga", year: 2020, personsAffected: 68 },
  { country: "Tonga", year: 2021, personsAffected: null },
  { country: "Tonga", year: 2022, personsAffected: null },
  { country: "Tonga", year: 2023, personsAffected: null },
  { country: "Tuvalu", year: 2005, personsAffected: null },
  { country: "Tuvalu", year: 2006, personsAffected: null },
  { country: "Tuvalu", year: 2007, personsAffected: null },
  { country: "Tuvalu", year: 2008, personsAffected: null },
  { country: "Tuvalu", year: 2009, personsAffected: null },
  { country: "Tuvalu", year: 2010, personsAffected: null },
  { country: "Tuvalu", year: 2011, personsAffected: 0 },
  { country: "Tuvalu", year: 2012, personsAffected: null },
  { country: "Tuvalu", year: 2013, personsAffected: null },
  { country: "Tuvalu", year: 2014, personsAffected: null },
  { country: "Tuvalu", year: 2015, personsAffected: 0 },
  { country: "Tuvalu", year: 2016, personsAffected: 1003 },
  { country: "Tuvalu", year: 2017, personsAffected: 0 },
  { country: "Tuvalu", year: 2018, personsAffected: 0 },
  { country: "Tuvalu", year: 2019, personsAffected: 0 },
  { country: "Tuvalu", year: 2020, personsAffected: 2266 },
  { country: "Tuvalu", year: 2021, personsAffected: 6 },
  { country: "Tuvalu", year: 2022, personsAffected: 7748 },
  { country: "Tuvalu", year: 2023, personsAffected: null },
  { country: "Vanuatu", year: 2005, personsAffected: 0 },
  { country: "Vanuatu", year: 2006, personsAffected: 0 },
  { country: "Vanuatu", year: 2007, personsAffected: 4 },
  { country: "Vanuatu", year: 2008, personsAffected: 60 },
  { country: "Vanuatu", year: 2009, personsAffected: 422 },
  { country: "Vanuatu", year: 2010, personsAffected: 500 },
  { country: "Vanuatu", year: 2011, personsAffected: 248 },
  { country: "Vanuatu", year: 2012, personsAffected: 28 },
  { country: "Vanuatu", year: 2013, personsAffected: 0 },
  { country: "Vanuatu", year: 2014, personsAffected: 152 },
  { country: "Vanuatu", year: 2015, personsAffected: 0 },
  { country: "Vanuatu", year: 2016, personsAffected: null },
  { country: "Vanuatu", year: 2017, personsAffected: 920 },
  { country: "Vanuatu", year: 2018, personsAffected: 23286 },
  { country: "Vanuatu", year: 2019, personsAffected: 18 },
  { country: "Vanuatu", year: 2020, personsAffected: 246802 },
  { country: "Vanuatu", year: 2021, personsAffected: 1400 },
  { country: "Vanuatu", year: 2022, personsAffected: null },
  { country: "Vanuatu", year: 2023, personsAffected: null },
  { country: "Wallis and Futuna", year: 2005, personsAffected: null },
  { country: "Wallis and Futuna", year: 2006, personsAffected: null },
  { country: "Wallis and Futuna", year: 2007, personsAffected: null },
  { country: "Wallis and Futuna", year: 2008, personsAffected: null },
  { country: "Wallis and Futuna", year: 2009, personsAffected: null },
  { country: "Wallis and Futuna", year: 2010, personsAffected: null },
  { country: "Wallis and Futuna", year: 2011, personsAffected: null },
  { country: "Wallis and Futuna", year: 2012, personsAffected: null },
  { country: "Wallis and Futuna", year: 2013, personsAffected: null },
  { country: "Wallis and Futuna", year: 2014, personsAffected: null },
  { country: "Wallis and Futuna", year: 2015, personsAffected: null },
  { country: "Wallis and Futuna", year: 2016, personsAffected: null },
  { country: "Wallis and Futuna", year: 2017, personsAffected: null },
  { country: "Wallis and Futuna", year: 2018, personsAffected: null },
  { country: "Wallis and Futuna", year: 2019, personsAffected: null },
  { country: "Wallis and Futuna", year: 2020, personsAffected: 0 },
  { country: "Wallis and Futuna", year: 2021, personsAffected: null },
  { country: "Wallis and Futuna", year: 2022, personsAffected: null },
  { country: "Wallis and Futuna", year: 2023, personsAffected: null },
];