// Direct disaster economic loss (USD) by Pacific Island Country/Territory and year. Source: direct_disaster_economic_loss.xlsx
const rawEconomicLossData = [
  { country: "Fiji", year: 2007, economicLoss: null },
  { country: "Fiji", year: 2010, economicLoss: 24623058 },
  { country: "Fiji", year: 2011, economicLoss: 1224504 },
  { country: "Fiji", year: 2012, economicLoss: 141400784 },
  { country: "Fiji", year: 2013, economicLoss: null },
  { country: "Fiji", year: 2014, economicLoss: null },
  { country: "Fiji", year: 2016, economicLoss: 374109863 },
  { country: "Fiji", year: 2018, economicLoss: 50247780 },
  { country: "Fiji", year: 2019, economicLoss: 1090125 },
  { country: "Fiji", year: 2020, economicLoss: 24247724 },
  { country: "French Polynesia", year: 2007, economicLoss: null },
  { country: "French Polynesia", year: 2010, economicLoss: null },
  { country: "French Polynesia", year: 2011, economicLoss: null },
  { country: "French Polynesia", year: 2012, economicLoss: null },
  { country: "French Polynesia", year: 2013, economicLoss: null },
  { country: "French Polynesia", year: 2014, economicLoss: null },
  { country: "French Polynesia", year: 2016, economicLoss: 30220000 },
  { country: "French Polynesia", year: 2018, economicLoss: null },
  { country: "French Polynesia", year: 2019, economicLoss: null },
  { country: "French Polynesia", year: 2020, economicLoss: null },
  { country: "Kiribati", year: 2007, economicLoss: null },
  { country: "Kiribati", year: 2010, economicLoss: null },
  { country: "Kiribati", year: 2011, economicLoss: null },
  { country: "Kiribati", year: 2012, economicLoss: null },
  { country: "Kiribati", year: 2013, economicLoss: null },
  { country: "Kiribati", year: 2014, economicLoss: 268950 },
  { country: "Kiribati", year: 2016, economicLoss: null },
  { country: "Kiribati", year: 2018, economicLoss: null },
  { country: "Kiribati", year: 2019, economicLoss: null },
  { country: "Kiribati", year: 2020, economicLoss: 30750 },
  { country: "Marshall Islands", year: 2007, economicLoss: 4.9 },
  { country: "Marshall Islands", year: 2010, economicLoss: null },
  { country: "Marshall Islands", year: 2011, economicLoss: null },
  { country: "Marshall Islands", year: 2012, economicLoss: null },
  { country: "Marshall Islands", year: 2013, economicLoss: null },
  { country: "Marshall Islands", year: 2014, economicLoss: 454125 },
  { country: "Marshall Islands", year: 2016, economicLoss: 1781682 },
  { country: "Marshall Islands", year: 2018, economicLoss: null },
  { country: "Marshall Islands", year: 2019, economicLoss: null },
  { country: "Marshall Islands", year: 2020, economicLoss: null },
  { country: "Micronesia (Federated States of)", year: 2007, economicLoss: null },
  { country: "Micronesia (Federated States of)", year: 2010, economicLoss: null },
  { country: "Micronesia (Federated States of)", year: 2011, economicLoss: null },
  { country: "Micronesia (Federated States of)", year: 2012, economicLoss: null },
  { country: "Micronesia (Federated States of)", year: 2013, economicLoss: null },
  { country: "Micronesia (Federated States of)", year: 2014, economicLoss: null },
  { country: "Micronesia (Federated States of)", year: 2016, economicLoss: 20310000 },
  { country: "Micronesia (Federated States of)", year: 2018, economicLoss: 196875 },
  { country: "Micronesia (Federated States of)", year: 2019, economicLoss: 8270325 },
  { country: "Micronesia (Federated States of)", year: 2020, economicLoss: null },
  { country: "New Caledonia", year: 2007, economicLoss: null },
  { country: "New Caledonia", year: 2010, economicLoss: null },
  { country: "New Caledonia", year: 2011, economicLoss: null },
  { country: "New Caledonia", year: 2012, economicLoss: null },
  { country: "New Caledonia", year: 2013, economicLoss: null },
  { country: "New Caledonia", year: 2014, economicLoss: null },
  { country: "New Caledonia", year: 2016, economicLoss: 20310000 },
  { country: "New Caledonia", year: 2018, economicLoss: null },
  { country: "New Caledonia", year: 2019, economicLoss: null },
  { country: "New Caledonia", year: 2020, economicLoss: null },
  { country: "Palau", year: 2007, economicLoss: null },
  { country: "Palau", year: 2010, economicLoss: null },
  { country: "Palau", year: 2011, economicLoss: null },
  { country: "Palau", year: 2012, economicLoss: 6190257 },
  { country: "Palau", year: 2013, economicLoss: null },
  { country: "Palau", year: 2014, economicLoss: null },
  { country: "Palau", year: 2016, economicLoss: 6 },
  { country: "Palau", year: 2018, economicLoss: null },
  { country: "Palau", year: 2019, economicLoss: null },
  { country: "Palau", year: 2020, economicLoss: null },
  { country: "Papua New Guinea", year: 2007, economicLoss: null },
  { country: "Papua New Guinea", year: 2010, economicLoss: null },
  { country: "Papua New Guinea", year: 2011, economicLoss: null },
  { country: "Papua New Guinea", year: 2012, economicLoss: 1077375 },
  { country: "Papua New Guinea", year: 2013, economicLoss: 1713195 },
  { country: "Papua New Guinea", year: 2014, economicLoss: null },
  { country: "Papua New Guinea", year: 2016, economicLoss: 9.57 },
  { country: "Papua New Guinea", year: 2018, economicLoss: null },
  { country: "Papua New Guinea", year: 2019, economicLoss: null },
  { country: "Papua New Guinea", year: 2020, economicLoss: 1593750 },
  { country: "Samoa", year: 2007, economicLoss: null },
  { country: "Samoa", year: 2010, economicLoss: null },
  { country: "Samoa", year: 2011, economicLoss: null },
  { country: "Samoa", year: 2012, economicLoss: null },
  { country: "Samoa", year: 2013, economicLoss: null },
  { country: "Samoa", year: 2014, economicLoss: null },
  { country: "Samoa", year: 2016, economicLoss: 22048411 },
  { country: "Samoa", year: 2018, economicLoss: null },
  { country: "Samoa", year: 2019, economicLoss: null },
  { country: "Samoa", year: 2020, economicLoss: null },
  { country: "Solomon Islands", year: 2007, economicLoss: null },
  { country: "Solomon Islands", year: 2010, economicLoss: 5826567 },
  { country: "Solomon Islands", year: 2011, economicLoss: 129938 },
  { country: "Solomon Islands", year: 2012, economicLoss: 1091496 },
  { country: "Solomon Islands", year: 2013, economicLoss: 12626951 },
  { country: "Solomon Islands", year: 2014, economicLoss: null },
  { country: "Solomon Islands", year: 2016, economicLoss: null },
  { country: "Solomon Islands", year: 2018, economicLoss: null },
  { country: "Solomon Islands", year: 2019, economicLoss: null },
  { country: "Solomon Islands", year: 2020, economicLoss: null },
  { country: "Tonga", year: 2007, economicLoss: null },
  { country: "Tonga", year: 2010, economicLoss: 4676174 },
  { country: "Tonga", year: 2011, economicLoss: 1113801 },
  { country: "Tonga", year: 2012, economicLoss: null },
  { country: "Tonga", year: 2013, economicLoss: null },
  { country: "Tonga", year: 2014, economicLoss: 18560063 },
  { country: "Tonga", year: 2016, economicLoss: 3050475 },
  { country: "Tonga", year: 2018, economicLoss: 8579025 },
  { country: "Tonga", year: 2019, economicLoss: null },
  { country: "Tonga", year: 2020, economicLoss: null },
  { country: "Vanuatu", year: 2007, economicLoss: null },
  { country: "Vanuatu", year: 2010, economicLoss: 3071588 },
  { country: "Vanuatu", year: 2011, economicLoss: 1470068 },
  { country: "Vanuatu", year: 2012, economicLoss: 281580 },
  { country: "Vanuatu", year: 2013, economicLoss: null },
  { country: "Vanuatu", year: 2014, economicLoss: 245100 },
  { country: "Vanuatu", year: 2016, economicLoss: 81.7 },
  { country: "Vanuatu", year: 2018, economicLoss: 64500000 },
  { country: "Vanuatu", year: 2019, economicLoss: null },
  { country: "Vanuatu", year: 2020, economicLoss: null },
];